version: '3.8'
services:
  pindrive-db:
    image: postgres:latest
    restart: "no"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    stop_signal: SIGTERM
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pindrive-db-data:/var/lib/postgresql/data

volumes:
  pindrive-db-data:
    driver: local
