import { Center } from '@mantine/core';
import type { NextPage } from "next";
import Head from "next/head";
import { Logo } from '../components/Logo/Logo';
import Welcome from '../components/Welcome/Welcome';
import ColorSchemeToggle from '../components/ColorSchemeToggle/ColorSchemeToggle';
import Layout from "./components/layout"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <>
          <Welcome />
          <Center>
            <Logo width={250} />
          </Center>
          <ColorSchemeToggle />
        </>
      </Layout>
    </>
  )
}

export default Home
