import type { NextPage } from "next";
import Head from "next/head";
import Welcome from '../components/Welcome/Welcome';
import ColorSchemeToggle from '../components/ColorSchemeToggle/ColorSchemeToggle';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <ColorSchemeToggle />
    </>
  );
};

export default Home;
